open-turo/actions-jvm

test/action.yaml
- Replaces `sdk env install` step in the `lint` action with the https://github.com/open-turo/action-setup-tools action
In particular, this will now install `sdk env install` if users specify `.sdkmanrc` in the repo
=> refactor(test): replace sdkman install w/ action-setup-tools

lint/README.md, lint/action.yaml
In current test action, Turo runs `./gradlew <action>`. In doing so, this often involves reading in artifactory credentials. However, this action doesn't have this information and needs the additional inputs from the user
- Add input parameters to the action for artifactory credentials
=> feat(lint): add artifactoryUsername and artifactoryAuthToken inputs

release/action.yaml
The current release action is a bit lacking because we can't utilize the semantic-release-action without setting up the tools.
However, setting up the tools requires checking out the repo so that we can read the environment / tools.
- Adds a setup tools step before starting the semantic-release-action and after checking out the repo.
=> [Release] Add step for setting up tools

release/action.yaml
- Output of the release step is not being assigned to the output of the action.
- Specify id of the release step so that the output can be used
=> fix(release): specify id so that output can be referenced

lint/action.yaml, release/action.yaml, test/action.yaml
`if: inputs.val == 'true'` is the same as `if: inputs.val` so lets use the simpler form throughout all of `open-turo` repos.
=> fix: do not need to explicitly test for true

release/action.yaml
To allow semantic release to use the passed github token to use git
**Changes**
* fix(release): don't persist credentials when checking out the repo
=> fix(release): don't persist credentials when checking out the repo

release/action.yaml
This updates the extra-plugins to default to `@open-turo/semantic-release-config@^1.4.0`.  This will
allow us to stop needing to configure it everywhere.
**Changes**
* fix(release): default extra-plugins to open-turo/semantic-release-config
=> fix(release): default extra-plugins to open-turo/semantic-release-config

lint/action.yaml
`inputs.checkout-repo` is a string and not a boolean, passing in false to the action right now has no effect as 
`if: inputs.checkout-repo` doesn't evaluate to false. 
Fixing this by updating the condition check to `if: inputs.checkout-repo == 'true'`
=> fix(lint): inputs.checkout-repo string comparison

test/README.md, test/action.yaml
In this PR, update test action to take in a gradle task input to run non-unit test tasks like integrationTest. 
The default for this input remains "test" task, there should be no changes to existing usage of this action.
=> feat(test): input for gradle test task

release/action.yaml, test/action.yaml
Existing check `if: inputs.checkout-repo` doesn't really do anything. 
Updating for string equality check like `if: inputs.checkout-repo == 'true'`
=> fix: input.checkout-repo == 'true'

prerelease-msvc/action.yaml
This passes the extra-plugins input through to the semantic-release step.
**Changes**
* fix(prerelease-msvc): passes extra-plugins through to semantic release
=> fix(prerelease-msvc): passes extra-plugins through to semantic release

.pre-commit-config.yaml, build-docker/README.md, lint/README.md, lint/action.yaml, prerelease-msvc/README.md, prerelease-msvc/action.yaml, release/README.md, script/update-action-readme, test/README.md
We have updated the actions-jvm to use open-turo/actions-release that supports working on pull request triggers.
This means that prerelease can run on pull request triggers.
It also means that we can include linting of release notes in our default lint action.
=> feat: allow prerelease & lint-release-notes to run on pull request trigger

build-docker/action.yaml
Per https://docs.docker.com/build/building/secrets/
> _Build arguments and environment variables are inappropriate for passing secrets to your build, because they persist in the final image. Instead, should use secret mounts or SSH mounts, which expose secrets to your builds securely._
As a migration step, this will pass tokens/keys as build secrets for secret while keeping the existing build-args until we can properly update Dockerfiles to use them.
=> feat: also pass credentials as build secrets

release/README.md, release/action.yaml
We no longer need to pin the default version, since we are using actions-release for release, which works with the latest version of the config
**Changes**
* fix(release): don't pin default semantic-release-config version
=> feat(release): don't pin default semantic-release-config version and use open-turo action

build-docker/README.md, build-docker/action.yaml
Allow build-docker composite action to configure following:
- whether the user wants to push an image to registry or just build an image
- whether the user wants to automatically load the single-platform build result to docker images
- support to dynamically input multiple build-args
- support to dynamically input multiple secrets
**Changes**
* feat(docker): support build-docker with push and load inputs
=> feat(docker): support build-docker with dynamically input multiple build-args and secrets

lint/action.yaml, prerelease-msvc/action.yaml, release/action.yaml
Update actions-release to v5. This failed on several repos on the first attempt, but after shipping https://github.com/open-turo/actions-release/pull/83 it's now working in some of our internal repos.
**Changes**
* feat: update to actions-release@v5
=> feat: update to actions-release@v5

build-docker/action.yaml
Pin version to fix CI for linux/arm64 docker build.
It’s a known bug from qemu. Pin it to tonistiigi/binfmt:qemu-v7.0.0-28 as suggested in
https://github.com/docker/setup-qemu-action/issues/201 , until the latest version has resolved it.
Multiple msvc repos have recently experienced the same error:
Related Discussion:
https://team-turo.slack.com/archives/C01BN39LHLH/p1740010908076559 
Fixes [#DEVOPS-12455](https://team-turo.atlassian.net//browse/DEVOPS-12455)
**Changes**
* fix(ci): pin version to qemu-v7.0.0-28
=> DEVOPS-12455: Pin version to fix CI for linux/arm64 docker build

lint/action.yaml
Passes github-token through to the pre-commit action to allow for fetching pre-commit hooks from private repos.
**Changes**
* fix(lint): adds github token to pre-commit for private repos
=> fix(lint): adds github token to pre-commit for private repos

test/action.yaml
remove sdkman command, since we are using setup-java(in action-setup-tools@v3) that install java version on the fly now
This will fix err related to the sdkman command as well
```
Run sdk current
/home/runner/_work/_temp/1b808e8b-b3d5-420c-bb9a-10e3303a1b23.sh: line 1: sdk: command not found
```
**Changes**
* fix: remove sdkman command
=> DEVX-200: remove sdkman from actions-jvm

build-docker/README.md, build-docker/action.yaml, prerelease-msvc/README.md, prerelease-msvc/action.yaml
Update pre-release to specify build platforms. The build-docker action has an image-platform field which can support a list, reuse it rather than having to release a new breaking version for multi platform builds.
Fixes [#DEVEX-11](https://team-turo.atlassian.net//browse/DEVEX-11)
**Changes**
* feat: support specifying build platforms for pre-release
=> DEVEX-11: Support multi platform builds on open-turo jvm actions
